version: "3.7"

services:
  app-teachy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teachy-challenge
    environment:
      - API_URL=https://swapi.dev/api
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
